CREATE TABLE ROLE 
(
	id SERIAL PRIMARY KEY,
	name VARCHAR(20)
);

CREATE TABLE USER_ROLE(
	USER_ID int,
	ROLE_ID int,
	FOREIGN KEY (user_id)
	REFERENCES AUTH_USER(id),
	FOREIGN KEY (role_id)
	REFERENCES role(id)
);
